import turtle

turtle.color("red")
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)
turtle.forward(60)
turtle.right(30)

turtle.hideturtle()
turtle.done()